
[files]
extend-exclude = ["pt-BR", "de", "ja", "es", "book/commands", "blog"]

[default.extend-words]
# Avoid the false positive in book/commands/str_replace.md
ons = "ons"
# Avoid false positive for json placeholder in cookbook/http.md
optio = "optio"
nushell = "nushell"
