name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - run: npm install
      # - run: npm run build
      - name: Build Static Docs
        env:
          NODE_OPTIONS: '--max_old_space_size=10240'
        run: npm run build
