name: Typos
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2

      - name: Check spelling of book
        uses: crate-ci/typos@master
        with:
          files: book

      - name: Check spelling of contributor book
        uses: crate-ci/typos@master
        with:
          files: contributor-book
